theme: jekyll-theme-cayman
title: Playing the Bad News Game
description: Prebunking Misinformation Practices in the Classroom with Gamification <br><br> Miles C. Coleman
github:
  is_project_page: false
